#!/bin/bash
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
python3.11 "scripts/explain.py" --metric AUC --continue_run True --model_type dpsgd
